include $(MTK_PATH_BUILD)/common.mk
#Fix-me: modified for early porting
#$(call all-subdir-src-or-makefile)
obj-y   += uart/
obj-y   += power/
obj-y	+= video/
#obj-y   += g2d/
#obj-y   += nand/
#obj-y   += gpu/
obj-y	+= i2c/
obj-y   += usb20/
obj-y   += keypad/
obj-y   += mau/
#obj-y   += touchpanel/
#obj-y   += accdet/
obj-y	+= rtc/
obj-y	+= sound/
#obj-y   += videocodec/
obj-y   += mmc-host/
#obj-y   += jpeg/
#obj-m   += m4u/
#obj-y	+= vibrator/
#obj-y   += ccci/
obj-y   += dum-char/
#obj-m   += cmmbdrv/
#obj-y   += spi/
#obj-y	+= spc/
#obj-y	+= power-loss-test/
