include $(MTK_PATH_BUILD)/common.mk
# Fix-me: modified for early porting
#$(call all-subdir-src-or-makefile)
obj-y	+= xlog/ aee/
obj-y   += wdk/
obj-y   += video/
obj-y   += usb20/
obj-y	+= hwmon/
obj-y	+= leds/
#obj-y   += m4u/
#obj-y   += videocodec/
#obj-y   += hdmitx/

ifeq ($(CONFIG_MTK_COMBO),m)
#obj-y	+= combo/
endif

#obj-$(CONFIG_MTK_GPS)	+= gps/
#obj-$(CONFIG_KEYBOARD_HID)	+= bthid/
#obj-y	+= ccci/
#obj-y   += ccmni/
#obj-y += net/
